spring:
  datasource:
    url: jdbc:h2:mem:testdb;mode=postgresql
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop