CREATE TABLE tb_account (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_sub_account (
    account_id BIGINT,
    account_type VARCHAR(100),
    balance DECIMAL(19, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_id, account_type),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES tb_account(id)
);

INSERT INTO tb_account (id, created_at) VALUES (123, CURRENT_TIMESTAMP), (124, CURRENT_TIMESTAMP), (125, CURRENT_TIMESTAMP), (126, CURRENT_TIMESTAMP);

INSERT INTO tb_sub_account (account_id, account_type, balance, created_at) VALUES
(123, 'FOOD', 5000.00, CURRENT_TIMESTAMP),
(123, 'MEAL', 5000.00, CURRENT_TIMESTAMP),
(123, 'CASH', 5000.00, CURRENT_TIMESTAMP),
(124, 'FOOD', 0, CURRENT_TIMESTAMP),
(124, 'MEAL', 0, CURRENT_TIMESTAMP),
(124, 'CASH', 0, CURRENT_TIMESTAMP),
(125, 'FOOD', 0, CURRENT_TIMESTAMP),
(125, 'MEAL', 10.00, CURRENT_TIMESTAMP),
(125, 'CASH', 3000.00, CURRENT_TIMESTAMP),
(126, 'FOOD', 0, NOW()),
(126, 'MEAL', 100.0, NOW()),
(126, 'CASH', 0, NOW());

CREATE TABLE tb_transaction (
    id SERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL,
    total_amount DECIMAL(19, 2) DEFAULT 0,
    mcc VARCHAR(4) NOT NULL,
    merchant VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES tb_account(id)
);

CREATE TABLE tb_merchant (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mcc VARCHAR(4) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO tb_merchant (id, name, mcc, created_at) VALUES
(100, 'UBER EATS SAO PAULO BR', '5811', CURRENT_TIMESTAMP);